name: build

on:
  push:
    branches: [ main ]   # only pushes to main create the dev tag

permissions:
  contents: read
  packages: write        # required to push to ghcr.io with GITHUB_TOKEN

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}   # e.g. kaelemc/clab-tailscale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Set up QEMU (for arm64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build amd64, push by digest
      - name: Build & push amd64 by digest
        id: build_amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE }},push-by-digest=true

      # Build arm64, push by digest
      - name: Build & push arm64 by digest
        id: build_arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE }},push-by-digest=true

      # Create and push the multi-arch manifest as :dev
      - name: Create & push dev manifest
        run: |
          set -euo pipefail
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE }}"
          AMD="${{ steps.build_amd64.outputs.digest }}"
          ARM="${{ steps.build_arm64.outputs.digest }}"
          docker buildx imagetools create \
            -t "${IMAGE}:dev" \
            "${IMAGE}@${AMD}" \
            "${IMAGE}@${ARM}"
